### ISSUE TITLE
pip install fails without cython installed

### ISSUE THREAD

**Issue by fcooper8472** [rajeshrinet/pystokes#8]
The instructions in the README to install using pip fail in a clean virtual environment.  To reproduce:

```
python3 -m venv venv
source venv/bin/activate
pip install pystokes
```

This fails due to
```
ModuleNotFoundError: No module named 'Cython'
```

This is due to `setup.py` requiring `Cython` before it gets around to installing it as a dependency.

See here for more info about the problem:
http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#basic-setup-py

I've not dealt with this directly before, but it might be sufficient to create a `pyproject.toml` as suggested.

**Comment by fcooper8472** [comment]
By the same token, `numpy` is also required by `setup.py`

**Comment by rajeshrinet** [comment]
@fcooper8472 it seems to work for me 

<img width="1307" alt="Screenshot 2020-06-23 at 21 27 29" src="https://user-images.githubusercontent.com/5037991/85457810-5a212700-b598-11ea-9f61-152a0731fec4.png">

could this be a linux vs mac issue?


PS:  also before pushing to pypi I always include
```python
install_requires=['cython','numpy','scipy'],
```

**Comment by fcooper8472** [comment]
Interesting: it seems to depend on whether pip's cache knows about pystokes already:
```
fergus@fergus:~/GitRepos/pystokes$ python3 -m venv venv2
fergus@fergus:~/GitRepos/pystokes$ source venv2/bin/activate
(venv2) fergus@fergus:~/GitRepos/pystokes$ pip install --no-cache-dir pystokes
Collecting pystokes
  Downloading pystokes-2.1.0.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/fergus/GitRepos/pystokes/venv2/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ey3m45u/pystokes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ey3m45u/pystokes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2ey3m45u/pystokes/pip-egg-info
         cwd: /tmp/pip-install-2ey3m45u/pystokes/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2ey3m45u/pystokes/setup.py", line 1, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv2) fergus@fergus:~/GitRepos/pystokes$ pip install pystokes
Processing /home/fergus/.cache/pip/wheels/a9/bd/20/78350583d5b8b48dd228cb795c015d497f366263e4699f9c20/pystokes-2.1.0-cp38-cp38-linux_x86_64.whl
Collecting cython
  Using cached Cython-0.29.20-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Collecting numpy
  Using cached numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
Collecting scipy
  Using cached scipy-1.5.0-cp38-cp38-manylinux1_x86_64.whl (25.7 MB)
Installing collected packages: cython, numpy, scipy, pystokes
Successfully installed cython-0.29.20 numpy-1.19.0 pystokes-2.1.0 scipy-1.5.0
(venv2) fergus@fergus:~/GitRepos/pystokes$ 
```

Are you able to reproduce my error with

```
pip install --no-cache-dir pystokes
```

or does it still work for you?

**Comment by rajeshrinet** [comment]
@fcooper8472 you are right. I can reproduce the error with 

```
pip install --no-cache-dir pystokes
```

**Comment by rajeshrinet** [comment]
@fcooper8472 I have now added a [pyproject.toml](https://github.com/rajeshrinet/pystokes/blob/master/pyproject.toml). Now the pip installation works even without cache. 

I also updated the [binder](https://github.com/rajeshrinet/pystokes/tree/master/binder) environment:

```python
name: pystokes
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - pystokes
```

I can confirm that it also works as expected. Thanks for your suggestions!

**Comment by fcooper8472** [comment]
Great!  Can confirm this is working for me as expected.  Thanks!
